Based on: https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html

In [1]:
import torch

In [2]:
torch.__version__

'1.6.0'

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 2.8026e-45, 0.0000e+00],
        [1.1210e-44, 0.0000e+00, 1.4013e-45]])


In [4]:
x = torch.rand(5, 3)

In [5]:
x

tensor([[0.6934, 0.6518, 0.6500],
        [0.7433, 0.5129, 0.5364],
        [0.9814, 0.6826, 0.5410],
        [0.6171, 0.3527, 0.8118],
        [0.5659, 0.1495, 0.3135]])

In [6]:
x.dtype

torch.float32

In [7]:
torch.tensor([5.5, 3])

tensor([5.5000, 3.0000])

In [8]:
torch.tensor([5.5, 3], dtype=torch.int)

<ipython-input-8-a4e3f208e6d0>:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  torch.tensor([5.5, 3], dtype=torch.int)


tensor([5, 3], dtype=torch.int32)

In [9]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)
x = torch.randn_like(x, dtype=torch.float) 
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


tensor([[-0.0177, -0.6481, -0.5716],
        [ 0.3277, -0.2202, -0.5585],
        [-0.2808,  0.1412,  0.5764],
        [ 1.1565, -0.2702,  1.3158],
        [-0.5148,  1.2649,  0.1209]])

In [10]:
x.size()

torch.Size([5, 3])

### Operations

In [11]:
y = torch.rand(5, 3)

We can save this use the torch funcions or Python operators

In [12]:
torch.add(x, y)

tensor([[ 0.5895, -0.0886, -0.2568],
        [ 1.2734,  0.5951, -0.3546],
        [-0.1085,  0.6815,  1.0367],
        [ 1.1772,  0.2961,  1.7311],
        [-0.0570,  1.3544,  1.0284]])

In [13]:
x + y

tensor([[ 0.5895, -0.0886, -0.2568],
        [ 1.2734,  0.5951, -0.3546],
        [-0.1085,  0.6815,  1.0367],
        [ 1.1772,  0.2961,  1.7311],
        [-0.0570,  1.3544,  1.0284]])

We can allocate the result and then use the `add` function to save the results to that tensor

In [14]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
result

tensor([[ 0.5895, -0.0886, -0.2568],
        [ 1.2734,  0.5951, -0.3546],
        [-0.1085,  0.6815,  1.0367],
        [ 1.1772,  0.2961,  1.7311],
        [-0.0570,  1.3544,  1.0284]])

We can do inplace operations

In [15]:
y.add_(x)

tensor([[ 0.5895, -0.0886, -0.2568],
        [ 1.2734,  0.5951, -0.3546],
        [-0.1085,  0.6815,  1.0367],
        [ 1.1772,  0.2961,  1.7311],
        [-0.0570,  1.3544,  1.0284]])

In [16]:
y.add_(x)

tensor([[ 0.5718, -0.7367, -0.8284],
        [ 1.6010,  0.3748, -0.9131],
        [-0.3893,  0.8227,  1.6131],
        [ 2.3337,  0.0259,  3.0469],
        [-0.5718,  2.6193,  1.1493]])

In [17]:
y += x
y

tensor([[ 0.5541, -1.3848, -1.4001],
        [ 1.9287,  0.1546, -1.4715],
        [-0.6701,  0.9639,  2.1895],
        [ 3.4902, -0.2443,  4.3627],
        [-1.0867,  3.8842,  1.2703]])

In [18]:
y += x
y

tensor([[ 0.5364, -2.0329, -1.9717],
        [ 2.2564, -0.0656, -2.0300],
        [-0.9509,  1.1050,  2.7658],
        [ 4.6468, -0.5145,  5.6786],
        [-1.6015,  5.1491,  1.3912]])

In [19]:
x[:, 1]

tensor([-0.6481, -0.2202,  0.1412, -0.2702,  1.2649])

In [20]:
x[:, 1][1]

tensor(-0.2202)

In [21]:
x[:, 1][1].item()

-0.22023223340511322

Reshape is view in pytorch

In [22]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(y)
print(z)

tensor([ 2.0345, -0.7967, -0.2509,  0.8094,  0.5240,  1.0042,  1.3220,  0.2160,
         1.4548, -2.0076, -0.9583, -1.3988, -0.6628, -0.2204, -0.8528, -0.3416])
tensor([[ 2.0345, -0.7967, -0.2509,  0.8094,  0.5240,  1.0042,  1.3220,  0.2160],
        [ 1.4548, -2.0076, -0.9583, -1.3988, -0.6628, -0.2204, -0.8528, -0.3416]])


In [23]:
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


### Numpy Bridge

Its the same memory for torch and numpy

In [24]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [25]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [26]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


It also works the other way

In [27]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
